@extends('layouts.app')
@section('title',$project->name)
@section('content')
<div class="toolbar"><div><span class="badge">{{$project->status}}</span> <span class="badge">PRIORIDAD {{$project->priority}}</span>@if($project->archived) <span class="badge archived-badge">ARCHIVADO</span>@endif<p>{{$project->description}}</p></div><div><a class="btn ghost" href="{{route('projects.edit',$project)}}">Editar</a> <form style="display:inline" method="POST" action="{{route('projects.archive',$project)}}" @if(!$project->archived) onsubmit="return confirm('¿Archivar {{$project->name}}?\n\nDejará de aparecer entre los proyectos activos, pero conservará toda su información y podrás restaurarlo desde Proyectos > Archivados.')" @endif>@csrf<button class="btn ghost">{{$project->archived?'Restaurar':'Archivar'}}</button></form></div></div>

@if($project->auto_progress && $project->plans->where('type','HITO')->where('status','!=','CANCELADO')->isEmpty())
<div class="warning-box">
    <div><strong>El avance automático está activo, pero este proyecto todavía no tiene hitos.</strong><br><span>Para mantenerlo simple, puedes usar avance manual o agregar solo unas pocas etapas importantes.</span></div>
    <div class="warning-actions"><a class="btn ghost" href="{{route('projects.edit',$project)}}">Usar avance manual</a><a class="btn" href="{{route('plans.create',['project_id'=>$project->id])}}">Agregar hito</a></div>
</div>
@endif

<div class="stats"><div><b>{{$project->progress}}%</b><span>Avance {{$project->auto_progress?'automático':'manual'}}</span></div><div><b>{{$project->credentials->count()}}</b><span>Credenciales</span></div><div><b>{{$project->urls->count()}}</b><span>Recursos</span></div><div><b>{{$project->plans->whereNotIn('status',['COMPLETADO','CANCELADO'])->count()}}</b><span>Pendientes</span></div></div>
<div class="grid2"><section class="panel"><h3>Próximo paso</h3><p>{{$project->next_step?:'No definido'}}</p><h3>Entorno técnico</h3><p><strong>Cliente:</strong> {{$project->client?:'—'}}<br><strong>Tecnologías:</strong> {{$project->technology?:'—'}}<br><strong>Entorno:</strong> {{$project->environment?:'—'}}<br><strong>Ruta:</strong> {{$project->local_path?:'—'}}<br><strong>Repositorio:</strong> @if($project->repository_url)<a href="{{$project->repository_url}}" target="_blank" rel="noopener">Abrir</a>@else — @endif</p><h3>Notas</h3><p class="pre">{{$project->notes?:'Sin notas'}}</p></section><section class="panel"><div class="toolbar"><div><h3>Hitos y planificación</h3><small>Opcional. Usa pocas etapas grandes si te resultan útiles.</small></div><a href="{{route('plans.create',['project_id'=>$project->id])}}">+ Agregar</a></div>@forelse($project->plans as $x)<div class="row"><a href="{{route('plans.edit',$x)}}"><span>{{$x->status==='COMPLETADO'?'✓':'○'}} {{$x->title}}</span><small>{{$x->type}} · {{$x->status}}@if($x->type==='HITO' && $project->auto_progress) · peso {{$x->weight}}@endif</small></a></div>@empty<p class="muted">Sin elementos. No es obligatorio crear hitos.</p>@endforelse</section></div>
<div class="grid2" style="margin-top:18px"><section class="panel"><div class="toolbar"><h3>Credenciales</h3><a href="{{route('credentials.create',['project_id'=>$project->id])}}">+ Agregar</a></div>@forelse($project->credentials as $x)<div class="row"><a href="{{route('credentials.edit',$x)}}"><strong>{{$x->label}}</strong><small>{{$x->category?:'Sin categoría'}}</small></a></div>@empty<p class="muted">Sin credenciales.</p>@endforelse</section><section class="panel"><div class="toolbar"><h3>URLs y recursos</h3><a href="{{route('urls.create',['project_id'=>$project->id])}}">+ Agregar</a></div>@forelse($project->urls as $x)<div class="row"><a href="{{$x->url}}" target="_blank" rel="noopener"><strong>{{$x->label}}</strong><small>{{$x->type}}</small></a></div>@empty<p class="muted">Sin recursos.</p>@endforelse</section></div>
@endsection
