<?php
namespace App\Http\Controllers;
use App\Models\{VaultSetting,Project,Credential,Plan,AuditLog}; use App\Services\{VaultCrypto,TotpService,AuditService}; use Illuminate\Http\Request; use Illuminate\Support\Facades\Crypt;
class VaultController extends Controller {
 public function login(){return view('auth.vault',['configured'=>VaultSetting::where('key','wrapped_dek')->exists()]);}
 public function setup(Request $r,VaultCrypto $c){abort_if(VaultSetting::where('key','wrapped_dek')->exists(),403);abort_unless(extension_loaded('sodium'),500,'NexoVault requiere la extensión Sodium.');$minimum=app()->environment('local')?8:12;$d=$r->validate(['password'=>['required','string','min:'.$minimum,'confirmed']]);$salt=random_bytes(SODIUM_CRYPTO_PWHASH_SALTBYTES);$kek=$c->derive($d['password'],$salt);$dek=random_bytes(SODIUM_CRYPTO_SECRETBOX_KEYBYTES);$w=$c->wrapKey($dek,$kek);VaultSetting::put('salt',base64_encode($salt));VaultSetting::put('wrapped_dek',$w['wrapped']);VaultSetting::put('wrap_nonce',$w['nonce']);$c->putSessionKey($dek);session(['vault_last_activity'=>time()]);AuditService::log('VAULT_CREATED','Bóveda inicializada.');return redirect()->route('dashboard')->with('ok','Bóveda creada.');}
 public function unlock(Request $r,VaultCrypto $c){$d=$r->validate(['password'=>'required']);try{$salt=base64_decode(VaultSetting::val('salt'));$kek=$c->derive($d['password'],$salt);$dek=$c->unwrapKey(VaultSetting::val('wrapped_dek'),VaultSetting::val('wrap_nonce'),$kek);if(VaultSetting::val('mfa_enabled')==='1'){session(['vault_pending_key'=>Crypt::encryptString(base64_encode($dek))]);return redirect()->route('vault.mfa');}$c->putSessionKey($dek);$r->session()->regenerate();session(['vault_last_activity'=>time()]);AuditService::log('VAULT_UNLOCKED','Bóveda desbloqueada.');return redirect()->route('dashboard');}catch(\Throwable){AuditService::log('VAULT_UNLOCK_FAILED','Intento fallido de desbloqueo.');return back()->withErrors(['master'=>'Contraseña maestra incorrecta.']);}}
 public function mfa(){abort_unless(session('vault_pending_key'),403);return view('auth.mfa');}
 public function verifyMfa(Request $r,VaultCrypto $c,TotpService $t){$d=$r->validate(['code'=>'required']);$dek=base64_decode(Crypt::decryptString(session('vault_pending_key')));$secret=$c->decrypt(VaultSetting::val('mfa_secret_enc'),$dek);$ok=$t->verify($secret,$d['code']);if(!$ok){$hashes=json_decode(VaultSetting::val('mfa_recovery_hashes')?:'[]',true);$h=hash('sha256',str_replace('-','',strtoupper(trim($d['code']))));$i=array_search($h,$hashes,true);if($i!==false){unset($hashes[$i]);VaultSetting::put('mfa_recovery_hashes',json_encode(array_values($hashes)));$ok=true;}}if(!$ok)return back()->withErrors(['code'=>'Código de autenticación incorrecto.']);session()->forget('vault_pending_key');$c->putSessionKey($dek);$r->session()->regenerate();session(['vault_last_activity'=>time()]);AuditService::log('MFA_VERIFIED','Segundo factor validado.');return redirect()->route('dashboard');}
 public function lock(Request $r){AuditService::log('VAULT_LOCKED','Bloqueo manual.');$r->session()->invalidate();$r->session()->regenerateToken();return redirect()->route('vault.login');}
 public function dashboard(){return view('dashboard',['projects'=>Project::where('archived',false)->latest()->take(8)->get(),'projectCount'=>Project::where('archived',false)->count(),'credentialCount'=>Credential::count(),'pendingCount'=>Plan::whereNotIn('status',['COMPLETADO','CANCELADO'])->count(),'avgProgress'=>(int)round(Project::where('archived',false)->avg('progress')??0),'recentLogs'=>AuditLog::latest()->take(6)->get(),'criticalPlans'=>Plan::with('project')->whereNotIn('status',['COMPLETADO','CANCELADO'])->orderBy('due_date')->take(6)->get()]);}
}
